### ISSUE TITLE
The output of "show ipv6 bgp summary" is unexpected if there is no IPv6 BGP session configured

### ISSUE THREAD

**Issue by kevinskwang** [sonic-net/sonic-utilities#2492]
#### Description

We saw some errors using CLI "show ipv6 bgp summary" as below:
  _$show ipv6 bgp sum
  Usage: show ipv6 bgp sum [OPTIONS]
  Try "show ipv6 bgp sum -h" for help.
  
  Error: bgp summary from bgp container in invalid format_

It will only happen on the devices which don't configure the IPv6 BGP session. 
IPv4 should be the same thing. 
 
## Steps to reproduce the issue
1. Make sure there isn't IPv6 BGP session configured in config_db 
2. Run CLI "config reload" 
3. Run CLI "show ipv6 bgp summary"
Then you should see above errors. Tried on branch 202205 and 202012.

#### Output of `show version`

```
(paste your output here)
```

**Comment by renukamanavalan** [comment]
Expected behavior:
The command to succeed with 0 neighbors reported.

A sample o/p from EOS/Arista:
EOS: (No v6 peers)
```
DB5-0101-0410-07BT0#show ipv6 bgp summ
BGP summary information for VRF default
Router identifier 172.16.97.146, local AS number 64607
Neighbor Status Codes: m - Under maintenance
  Neighbor         V  AS           MsgRcvd   MsgSent  InQ OutQ  Up/Down State  PfxRcd PfxAcc
DB5-0101-0410-07BT0#
```

**Comment by gechiang** [comment]
For the MultiASIC support there is some preprocessing going on and it is treating this case as an error case.
Ideally it should behave the same as if this was executed directly from inside the bgp docker and when there is no no IPV6 or IPV4 configured, it should have the following output:
```
admin@SONIC:/etc/sonic$ docker exec -it bgp bash
root@SONIC:/# vtysh -c "show bgp ipv6 sum"
% No BGP neighbors found in VRF default
root@SONIC:/#
```

@arlakshm will help fix this to make it behave the same way instead of printing the error message thinking that it is a malformed json having invalid format.
